settings:
    ck: 'Wi8HzqA5JLUfxezSWsrZuTOpn'
    cs: 'MSMGgUckPuitr4pZvntPvQrtktpSYqSoeGtkMlNMZowsxxJ7Yn'
    at: '587344296-xZE6OWbAGN5fdbfOFkhRaOgTH1j7czfXEKQJPchl'
    ats: 'MZF0NZz3hMuUHvFobROrwvB1og1MjWay6HiOIYwvFNiW6'